config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:show, :index, :new, :create, :destroy] do
  resources :doses, only: [:create, :destroy]
  end
  resources :ingredients, only: [:show]

  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: 'Cocktail was successfully added!'
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to @cocktail, notice: 'Cocktail was successfully deleted'
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :set_cocktail

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def show
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, placeholder: "Mojito" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/cocktails/index.html.erb
<h1 class="text-center">Your cocktail list</h1>

<div class="text-center padded">
  <%= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card text-center">


          <% if cocktail.picture %>
            <div class="card-header" style="background-image: url('<%= image_path cocktail.picture%>')">
            </div>
          <% else %>
            <div class="card-header" style="background-image: url('http://www.seriouseats.com/images/2014/11/20141104-cocktail-party-old-fashioneds-holiday-vicky-wasik-3.jpg')">
            </div>
          <% end %>
          <div class="card-body">
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Cocktail</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <%= link_to 'Back', cocktails_path %>

      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li>
            <%= dose.description %> of <%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %>
            (<%= link_to "delete", cocktail_dose_path(@cocktail, dose), method: :delete %>)
          </li>
        <% end %>
      </ul>

      <%= simple_form_for [@cocktail, @dose] do |f| %>

        <% if @dose.errors.any? %>
          <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>

        <%= f.input :description, placeholder: "2 teaspoons" %>
        <%= f.input :ingredient_id, collection: Ingredient.all, prompt: "Choose one" %>

        <%= f.submit "Add dose", class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<h1>Details about <%= @ingredient.name %></h1>

<p>Here are the cocktails you can make with it:</p>

<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
    <li><%= cocktail.name %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>